name: Deploy to Render

on:
  push:
    branches:
      - main
      - feature/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy (repo-level)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID_PROD: ${{ secrets.RENDER_SERVICE_ID_PROD }}
          RENDER_SERVICE_ID_TEST: ${{ secrets.RENDER_SERVICE_ID_TEST }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          set -e
          # Only deploy prod on main
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            if [ -z "$RENDER_SERVICE_ID_PROD" ] || [ -z "$RENDER_API_KEY" ]; then
              echo "Missing RENDER_SERVICE_ID_PROD or RENDER_API_KEY; skipping prod deploy"
              exit 0
            fi
            echo "Triggering prod deploy..."
            curl -s -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID_PROD}/deploys" \
              -H "Authorization: Bearer ${RENDER_API_KEY}" \
              -H "Content-Type: application/json" \
              -d '{"clearCache":true}'
          else
            # For other branches, attempt to trigger test service
            if [ -z "$RENDER_SERVICE_ID_TEST" ] || [ -z "$RENDER_API_KEY" ]; then
              echo "Missing RENDER_SERVICE_ID_TEST or RENDER_API_KEY; skipping test deploy"
              exit 0
            fi
            echo "Triggering test deploy..."
            curl -s -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID_TEST}/deploys" \
              -H "Authorization: Bearer ${RENDER_API_KEY}" \
              -H "Content-Type: application/json" \
              -d '{"clearCache":true}'
