name: Generate package-lock.json

on:
  push:
    branches:
      - chore/add-lockfile

jobs:
  generate-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies to generate lockfile
        run: npm install --package-lock-only

      - name: Upload generated package-lock.json
        uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json

      - name: Commit and push package-lock.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: generate package-lock.json"
            git push origin HEAD:chore/add-lockfile
          fi
