name: PR preview smoke test

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  find-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check required tools
        run: |
          sudo apt-get update -y >/dev/null
          sudo apt-get install -y jq curl >/dev/null

      - name: Skip if PR requests no preview
        run: |
          # Exit early if PR title contains [skip preview] (case-insensitive)
          if [ -n "${GITHUB_EVENT_PATH:-}" ] && command -v jq >/dev/null 2>&1; then
            TITLE=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH" || echo "")
            echo "PR title: $TITLE"
            if echo "$TITLE" | grep -qi '\[skip preview\]'; then
              echo "Skipping preview workflow due to title marker"
              exit 0
            fi
            # Check labels for render-preview-skip
            LABEL_MATCH=$(jq -r '.pull_request.labels[]?.name' "$GITHUB_EVENT_PATH" 2>/dev/null | grep -E '^render-preview-skip$' || true)
            if [ -n "$LABEL_MATCH" ]; then
              echo "Skipping preview workflow due to label: $LABEL_MATCH"
              exit 0
            fi
          else
            echo "No event payload or jq missing; continuing"
          fi

      - name: Ensure Render API key exists
        if: ${{ !secrets.RENDER_API_KEY }}
        run: |
          echo "RENDER_API_KEY secret is not set; skipping preview lookup and smoke test"
          exit 0

      - name: Find Render preview service for this PR branch (polling)
        id: find_service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          BRANCH: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          set -euo pipefail
          # If the Render API key is not available (for example, PR from a fork), post an informational note and exit.
          if [ -z "${RENDER_API_KEY:-}" ]; then
            echo "RENDER_API_KEY is not available in this workflow (likely a forked PR)."
            echo "service_found=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Looking up Render services for branch: $BRANCH (PR #$PR_NUMBER)"
          MAX_ATTEMPTS=12
          SLEEP_SECS=10
          attempt=0
          found="false"
          preview_url=""
          service_id=""
          service_name=""
          while [ $attempt -lt $MAX_ATTEMPTS ]; do
            attempt=$((attempt+1))
            echo "Attempt $attempt/$MAX_ATTEMPTS: querying Render services..."
            services=$(curl -s -H "Authorization: Bearer ${RENDER_API_KEY}" https://api.render.com/v1/services)
            # Try multiple matching strategies in order:
            # 1) Service name contains PR number (common for preview names)
            # 2) Branch matches exactly
            # 3) Service url or name contains branch name
            match=$(echo "$services" | jq -r --arg PR "$PR_NUMBER" --arg BRANCH "$BRANCH" '
              (.[ ] | select(.name | test("pr[-_ ]?" + $PR; "i"))) as $byPr |
              (.[ ] | select(.branch == $BRANCH)) as $byBranch |
              (.[ ] | select((.name // "" | test($BRANCH; "i")) or (.serviceDetails.url // "" | test($BRANCH; "i")))) as $byName |
              [$byPr, $byBranch, $byName] | map(select(. != null)) | .[0] | {id: .id, name: .name, branch: .branch, url: (.serviceDetails.url // .serviceDetails.defaultDomain // .serviceDetails.defaultIngress // .url // .defaultDomain // .externalUrl // .service_url // empty)}' | jq -s '.[0]') || true
            if [ -n "$match" ] && [ "$match" != "null" ]; then
              found="true"
              service_id=$(echo "$match" | jq -r '.id') || true
              service_name=$(echo "$match" | jq -r '.name') || true
              preview_url=$(echo "$match" | jq -r '.url // ""') || true
              echo "Found service: $service_name ($service_id) with URL: $preview_url"
              break
            fi
            echo "No matching service yet. Sleeping $SLEEP_SECS seconds..."
            sleep $SLEEP_SECS
          done

          if [ "$found" = "true" ]; then
            echo "service_found=true" >> $GITHUB_OUTPUT
            echo "preview_url=$preview_url" >> $GITHUB_OUTPUT
            echo "service_id=$service_id" >> $GITHUB_OUTPUT
            echo "service_name=$service_name" >> $GITHUB_OUTPUT
          else
            echo "service_found=false" >> $GITHUB_OUTPUT
            echo "No service matching branch $BRANCH found after $MAX_ATTEMPTS attempts. Dumping services for debugging..."
            echo "$services" | jq -C '.[] | {id: .id, name: .name, branch: .branch}' || true
            # Upload services json for debugging
            echo "$services" > services.json || true
            echo "services.json created"
          fi

      - name: Upload services debug artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: services-json
          path: services.json

      - name: RENDER_API_KEY missing notice (fork-safe)
        if: ${{ env.RENDER_API_KEY == '' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # If this run cannot access RENDER_API_KEY (common for fork PRs), post a note to the PR explaining why we couldn't fetch the preview URL
          TITLE="Render preview lookup skipped"
          BODY="This workflow couldn't access the Render API key in this run (likely because this PR is from a fork). As a result, the preview service lookup and smoke test were skipped. If you need a preview, please trigger the preview from the base repo or ask an admin to run the workflow."
          OWNER=$(jq -r .pull_request.head.repo.owner.login "$GITHUB_EVENT_PATH" 2>/dev/null || echo "${{ github.repository_owner }}")
          REPO=$(jq -r .pull_request.head.repo.name "$GITHUB_EVENT_PATH" 2>/dev/null || echo "${{ github.event.repository.name }}")
          PR=${PR_NUMBER}
          payload=$(jq -n --arg body "$BODY" '{body: $body}')
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST "https://api.github.com/repos/${OWNER}/${REPO}/issues/${PR}/comments" -d "$payload" || true

      - name: Post preview URL to PR (post to head repo for forked PRs)
        if: steps.find_service.outputs.service_found == 'true' && steps.find_service.outputs.preview_url != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          URL=${{ steps.find_service.outputs.preview_url }}
          # Determine the correct repo to post to: use pull_request.head.repo if available (handles forks)
          OWNER=$(jq -r .pull_request.head.repo.owner.login "$GITHUB_EVENT_PATH" 2>/dev/null || echo "${{ github.repository_owner }}")
          REPO=$(jq -r .pull_request.head.repo.name "$GITHUB_EVENT_PATH" 2>/dev/null || echo "${{ github.event.repository.name }}")
          PR_NUMBER=$(jq -r .pull_request.number "$GITHUB_EVENT_PATH" 2>/dev/null || echo "${{ github.event.number }}")
          echo "Posting preview URL to ${OWNER}/${REPO} PR #${PR_NUMBER}: $URL"
          payload=$(jq -n --arg body "Render preview: $URL" '{body: $body}')
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST "https://api.github.com/repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" -d "$payload" >/dev/null || true

      - name: Run smoke test against preview URL (retry until 200)
        id: smoke_test
        if: steps.find_service.outputs.service_found == 'true' && steps.find_service.outputs.preview_url != ''
        env:
          PREVIEW_URL: ${{ steps.find_service.outputs.preview_url }}
        run: |
          echo "Pinging preview URL with retries: $PREVIEW_URL"
          MAX_RETRIES=12
          SLEEP_SECONDS=5
          attempt=0
          passed=false
          while [ $attempt -lt $MAX_RETRIES ]; do
            attempt=$((attempt+1))
            status=$(curl -s -o /dev/null -w "%{http_code}" "$PREVIEW_URL" ) || true
            echo "Attempt $attempt: HTTP $status"
            if [ "$status" -ge 200 ] && [ "$status" -lt 400 ]; then
              echo "Preview smoke test passed (status $status)"
              passed=true
              break
            fi
            echo "Not ready yet, sleeping $SLEEP_SECONDS seconds..."
            sleep $SLEEP_SECONDS
          done
          if [ "$passed" != "true" ]; then
            echo "Preview smoke test failed after $MAX_RETRIES attempts"
            exit 1
          fi

      - name: Publish PR Preview Smoke Test check run (pass/fail)
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const outcome = '${{ steps.smoke_test.outcome }}';
            const headSha = (context.payload.pull_request && context.payload.pull_request.head && context.payload.pull_request.head.sha) || context.sha;
            const conclusion = outcome === 'success' ? 'success' : 'failure';
            const title = 'PR Preview Smoke Test';
            const summary = outcome === 'success' ? 'Preview smoke test passed' : 'Preview smoke test failed';
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: title,
              head_sha: headSha,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: title,
                summary: summary,
                text: `Outcome: ${outcome}`
              }
            });

      - name: No preview found (info)
        if: steps.find_service.outputs.service_found != 'true'
        run: |
          echo "No preview service was found for branch ${{ github.head_ref }}. Render may not have created it yet or naming differs."
